version: '2.1'

services:

  gdelt_create_index:
    build: .
    image: sofwerx/es-delt
    container_name: gdelt_create_index
    hostname: gdelt_create_index
    environment:
      ES_HOST: ES_HOST
      ES_USER: ${ES_USER}
      ES_PASSWORD: ${ES_PASSWORD}
      ES_DELETE_INDEX: N
    command: python gdelt_create_index.py

